"""relação das tabelas pedidos e itens pedidos

Revision ID: 4ffedcb0ed19
Revises: 8505ab72ab6d
Create Date: 2025-08-26 14:37:46.745370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffedcb0ed19'
down_revision: Union[str, Sequence[str], None] = '8505ab72ab6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
