"""initial

Revision ID: f23aaf4afc49
Revises: 
Create Date: 2025-08-27 20:10:08.317500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23aaf4afc49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('pendente', 'finalizado', 'cancelado', name='status_enum'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pedidos.id', 'pedidos', ['id'], unique=False)
    op.create_index('ix_pedidos.status', 'pedidos', ['status'], unique=False)
    op.create_index('ix_pedidos.usuario_id', 'pedidos', ['usuario_id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.Column('tamanho', sa.String(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itens_pedido.id', 'itens_pedido', ['id'], unique=False)
    op.create_index('ix_itens_pedido.pedido_id', 'itens_pedido', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itens_pedido.pedido_id', table_name='itens_pedido')
    op.drop_index('ix_itens_pedido.id', table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index('ix_pedidos.usuario_id', table_name='pedidos')
    op.drop_index('ix_pedidos.status', table_name='pedidos')
    op.drop_index('ix_pedidos.id', table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
